config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  resources :things
  get 'fields/add_field' => "things#add_field"

  root 'things#new'

end

app/models/thing.rb
class Thing < Substance
  
  include Inputable
  include Insertable
  ## hash
  ## key[string] -> entry id
  ## value[integer] -> time updated or created.
  ## this hash is written to from the after_save callback of the entry.rb class 
  field :entries, type: Hash, default: {}

  ##@used_in : things/_thing_inputs.html.erb
  ##@process: if the first input exists in the database then 
  def has_inputs?
    load_inputs
    return self.loaded_inputs_array.size > 0
  end

  ##@used_in: things/_thing_inputs.html.erb
  ##@process: loads the inputs from the database into the accessor element "Inputable.loaded_inputs_array"
  def load_inputs
    self.loaded_inputs_array = self.inputs.map{|c| 
      begin
        c = Input.find(c)
      rescue
        nil
      end
    }.compact
  end

  def to_schema
    super.tap do |defintion|
      definition["_id"] = self.id.to_s
    end
  end


  def rebuild_es_mapping(document)
    super.tap do |mapping|
      if self.es_mapping["properties"][document.title].nil?
        self.es_mapping["properties"][document.title] = document.to_es_mapping
      end
    end
  end



end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  respond_to :html,:js

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new(permitted_params)
    @p_id = Node.new.id.to_s
    @parent_p_id = "root"
    @p_type = "string"
    respond_with @thing
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)
    @thing.save
    render :partial => "thing_created.js.erb", :locals => {:thing => @thing}, :formats => [:js]
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ##expected parameter is :parent_piece_id
  def add_field
    p = permitted_params
    @parent_p_id = p[:parent_piece_id].nil? ? "root" : p[:parent_piece_id] 
    @p_id = Node.new.id.to_s
    #@p_type = (@parent_piece_id == "root") ? "string" : "object"  
    @p_type = "string"
    render :partial => "piece.html.erb", :formats => [:js], :locals => {:piece_id => @p_id, :parent_piece_id => @parent_p_id, :piece_type => @p_type}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :pieces => [:piece_id , :parent_piece_id, :title, :description, :default, :maxLength, :minimum, :maximum, :exclusiveMinimum, :exclusiveMaximum, :readOnly, :required, :type, :enum])
    end

    ##while requesting a piece, the parent piece id must be provided.
    def permitted_params
      if action_name.to_s == "add_field"
        params.permit(:parent_piece_id,:div_id)
      elsif action_name.to_s == "new"
        params.permit(:name,:div_id)
      elsif action_name.to_s == "create" || action_name.to_s == "update"
        params.require(:thing).permit(:parent)
      end
    end

    ##returns a unique id for each piece that is requestd.
    def get_piece_id
      return Time.now.to_i.to_s
    end


end 

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <%= render :partial => "piece_wrapper", locals: {:p_id => @p_id, :parent_p_id => @parent_p_id, :p_type => @p_type} %>

  <div class="actions" style="margin-top:30px;">
    
  </div>
<% end %>

<%= render 'thing_inputs' %>  

<button id="create_thing">
    <i class="fa fa-spin fa-refresh" id="create_thing_spinner" style="display:none;"></i>
    Create Thing
</button>

app/views/things/_mcq_modal.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Multiple Choice Options</h4>
</div>
<div class="modal-body">
    <p>Add the options for your field here.</p>
    <p class="text-warning"><small>When you are done typing an option, just press enter and then add another one.</small></p>
    <input type="text" value="" data-role="tagsinput" class="mcq_options_field"/> 
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <!-- on clicking this it should also do data-dismiss, and on the nearest piece, it should store the enum options. -->
    <button type="button" class="btn btn-primary mcq_options_confirm">Save changes</button>
</div>

app/views/things/_modal.html.erb
<div id="business_modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= yield %>
        </div>
    </div>
</div>

app/views/things/_piece.html.erb
<div class="piece bg-info" data-piece-id="<%= piece_id %>" data-parent-piece-id="<%= parent_piece_id %>" data-piece-type="<%= piece_type %>" style="padding:20px; margin-top:1px; width:50%;">
	<div class="row">
		<div class="col-xs-2 col-lg-2">
			<!-- field title -->
			<div style="margin-bottom: 10px;">FIELD-NAME</div>
			<input type="text" class="piece_name" style="width:100%;"></input>
			<!-- field description -->
			<div style="margin-top: 20px; margin-bottom:10px;">Description</div>
			<input type="text" class="piece_description" style="width:100%"></input>
		</div>
		<div class="col-xs-6 col-lg-5">
			<div>FIELD-TYPE</div>
			<div class="radio">
			  <label>
			    <input type="radio" name="optionsRadios_<%= piece_id %>" class="ft_text" value="string" checked>
			     Text
			  </label>
			</div>
			<div class="radio">
			  <label>
			    <input type="radio" name="optionsRadios_<%= piece_id %>" class="ft_numeric" value="number">
			    Numeric
			  </label>
			</div>
			<div class="radio">
			  <label>
			    <input type="radio" name="optionsRadios_<%= piece_id %>" class="ft_timestamp" value="number">
			    TimeStamp
			  </label>
			</div>
			<div class="radio">
			  <label>
			    <input type="radio" name="optionsRadios_<%= piece_id %>" class="ft_mcq" value="string">
			    Multiple-Choice-Options
			  </label>
			</div>
			<div class="radio">
			  <label>
			    <input type="radio" name="optionsRadios_<%= piece_id %>" class="ft_array" value="array">
			    There will be more than one of this field.
			  </label>
			</div>
		</div>
	</div>
	<div style="margin-bottom:30px"></div>
	
	<button type="button" class="btn btn-primary add_subfield">Add Sub-Field</button>
	<button type="button" class="btn btn-primary add_field_datasource">Add Datasource</button>
	<button type="button" class="btn btn-primary add_field_modules">Add Modules</button>
	<button type="button" class="btn btn-danger remove_field">Remove This Field</button>
	<!-- modal for the mcq options -->
	<%= render partial: 'mcq_modal', layout: 'modal' %> 
	<!-- ends -->
</div>

app/views/things/_piece_wrapper.html.erb
<div style="display:none">
	<h6 style="margin-bottom:10px; margin-top:40px;"><b>Fields</b></h6>
	  
	<div id="pieces">
	<%= render 'piece', :piece_id => p_id, :parent_piece_id => parent_p_id, :piece_type => p_type %>
	</div>

	<button type="button" class="btn btn-primary" style="margin-top:20px;" id="add-piece">Add Another Field</button>
</div>

app/views/things/_thing_created.js.erb
try{
$("#create_thing_spinner").hide();
var q = ("<%= thing.to_json %>");

var j = $("<div/>").html(q).text();

j = JSON.parse(j);

$("#business_form").jsonForm(j);

}
catch(err){
	console.log(err);
}

app/views/things/_thing_inputs.html.erb
<% if @thing.has_inputs? %>  
  <h4><%= @thing.name %> has the following fields:</h4>
  <div id="inputs">
    <% @thing.loaded_inputs_array.each do |i| %>
      <%= render 'inputs/thing_field_show', locals: {:input => i} %>
    <% end %>
  </div>
<% else %>
  <h4><%= @thing.name %> currently has no fields, add some</h4>
<% end %>

<%= render 'inputs/thing_field_new' %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Things</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Schema</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= thing.schema %></td>
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form' %>

<form id="business_form" style="margin-top:30px;"></form>


<%= link_to 'Back', things_path %>

app/views/things/new.js.erb
var div_id = "#<%= @thing.div_id %>";
$(div_id).append("<%= escape_javascript(render 'form') %>");

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Schema:</strong>
  <%= @thing.schema %>
</p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>