config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  resources :things
  get 'fields/add_field' => "things#add_field"

  root 'things#new'

end

app/models/input.rb
class Input
  include Suggestable
  include Insertable
  ##each input is for a particular array of purposess.
  ##each purpose is an es id.
  ##each purpose can either be a thing, field, action or process id.
  field :input_for, type: Array, default: []
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy]
  respond_to :html,:js
  # GET /inputs
  # GET /inputs.json
  def index
    @inputs = Input.all
  end

  # GET /inputs/1
  # GET /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
    if !params[:div_id].nil?
      @input.div_id = params[:div_id]
    end
    @input
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs
  # POST /inputs.json
  def create
    @input = Input.new(input_params)  
    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: 'Input was successfully created.' }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /inputs/1
  # PATCH/PUT /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: 'Input was successfully updated.' }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1
  # DELETE /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: 'Input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_params
      params.require(:input).permit(:sentence,:div_id,{:input_for => []})
    end

    def permitted_params
      params.permit(:div_id)
    end 

end

app/helpers/inputs_helper.rb
module InputsHelper
	
	## input consists of an array of embedded suggestion objects. 
	## there many be more than one suggestion for the same search_fragment.
	## this method first builds a hash out of the suggestion array.
	## this prepares it for the view.
	
	## @param[Array] : suggestions array
	## @return[Hash] : suggestions hash, key -> search fragment, value ->  suggestions array for that fragment
	def build_suggestion_hash

	end
	
end

app/views/inputs/_form.html.erb
<%= form_for(@input) do |f| %>
  <% if @input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% @input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.text_area :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inputs/_thing_field_new.html.erb
<% unless @input %>
  <% @input = Input.new %>
<% end %>
<%= form_for(@input, remote: true) do |f| %>
  <% if @input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% @input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :sentence, {placeholder: "e.g It can have a name", id: @input.id.to_s + "_sentence", class: "sentence"} %>
  </div>
<% end %>

app/views/inputs/_thing_field_show.html.erb
<%= input.sentence %>
<%= link_to 'Edit', edit_input_path(input) %>

app/views/inputs/edit.html.erb
<h1>Editing Input</h1>

<%= render 'form' %>

<%= link_to 'Show', @input %> |
<%= link_to 'Back', inputs_path %>

app/views/inputs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inputs</h1>

<table>
  <thead>
    <tr>
      <th>Sentence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inputs.each do |input| %>
      <tr>
        <td><%= input.sentence %></td>
        <td><%= link_to 'Show', input %></td>
        <td><%= link_to 'Edit', edit_input_path(input) %></td>
        <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input', new_input_path %>

app/views/inputs/new.html.erb
<h1>New Input</h1>

<%= render 'form' %>

<%= link_to 'Back', inputs_path %>

app/views/inputs/new.js.erb
var div_id = "#<%= @input.div_id %>";
$(div_id).append("<%= escape_javascript(render 'new') %>");

app/views/inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>You typed:<%= @input.sentence %></strong>
  <br>
  <b>Click on the words underlined in red, to build Things from, this is the first step to creating your software.</b>
  <br>
  <%= highlight(@input.sentence,@input.tgr.get_nouns(@input.tagged).keys,highlighter: '<em>\1</em>'){|match| link_to(match,new_thing_path(div_id: match, name: match),{remote: true, class: "prospective_thing"})} %>
  
  <% @input.tgr.get_nouns(@input.tagged).keys.each do |n| %>
  	<div id="<%= n.to_s %>" class="thing"></div>
  <% end %>
</p>

<%= link_to 'Edit', edit_input_path(@input) %> |
<%= link_to 'Back', inputs_path %>